### PR TITLE
A little improvement of error feedback

### PR DESCRIPTION
**Pull request by krichter722**

### CODE REVIEW

**Comment by marcindulak** [comment]
Hi, any progress here?

**Comment by raphink** [comment]
Sorry about that. Looks good to me. Can you just squash the two commits please?

**Comment by raphink** [comment]
Actually, what's the reason for changing the type of exception?

**Comment by krichter722** [comment]
On the one hand raising an IOError makes sense because we don't succed to write the file (I/O + error = IOError), on the other the reason for the exception is lost because we simple check the return code of `augeas` which doesn't reveal the reason for the failure, i.e. we're breaking the exception chain and thus should raise the most abstract error (= Error) because an error unrelated to I/O might have occured.

**Comment by raphink** [comment]
Is this worth a breaking change though?

**Comment by krichter722** [comment]
> Is this worth a breaking change though?

I don't know myself. Might be better for the project to close this.

**Comment by raphink** [comment]
Well I don't mind the error message being more specfic, that's useful. Just changing the exception type is a breaking change, since there might be people specifically catching `IOError` currently

**Pull request closed without merging**
