### PR TITLE
Add load_file, source, srun to the API

### PR DESCRIPTION
**Pull request by georgehansper**
Added the following API calls:

load_file()
   eg load_file('/etc/hosts')
source()
   eg source('/files/etc/hosts/1/ipaddr')
srun()
   eg srun(sys.stdout,'print /augeas//error')

### CODE REVIEW

**Comment by raphink** [comment]
LGTM, but I wonder why the build fails.

**Comment by georgehansper** [comment]
I think it might be the version of augeas that travis is using.

I was testing it on Fedora 31, augeas-1.12.0-2.fc31

**Comment by georgehansper** [comment]
The current set of test work against the current release of Augeas (1.12.0)
The issue with Travis is that it does not support the most recent release of Augeas.

Is passing Travis CI required for this Pull Request to be accepted ?

**Comment by thedrow** [comment]
> The current set of tests work against the current release of Augeas (1.12.0)
> The issue with Travis CI is that it does not support the most recent release of Augeas.
> 
> Is passing Travis CI required for this Pull Request to be accepted ?

Yes.

**Comment by georgehansper** [comment]
This Pull Request is now passing it's Travis CI tests,

**Pull request merged**
