### PR TITLE
Add Python 3.6 and drop 2.6 and 3.3

### LINKED ISSUE #31: Drop Python 2.6 support
We'd rather support only modern python versions.
For compatibility, users should use an older version. Probably 0.5.

### PR DESCRIPTION
**Pull request by hugovk**
Resolves #31.

Also removed some unused imports, variables and semicolons.

### CODE REVIEW

**Comment by hugovk** [comment]
@thedrow Hello, any thoughts on this PR? Thank you!

**Comment by thedrow** [comment]
Thanks!

**Comment by lutter** [comment]
How do we make sure that this doesn't break users, especially Let's Encrypt ? RHEL6 still has python-2.6.6 on it, and we can't break that.

Before this gets released, please coordinate with @bmw and @jinhooi to make sure it does not break them - and if it does, please revert this

**Comment by hugovk** [comment]
One option is they pin to the currently released version that still supports 2.6.

**Comment by lutter** [comment]
I am not a fan of forcing users to pin, especially since it locks them out from other improvements, e.g. new augeas API calls. It also requires that they learn about what to pin to and therefore creates more friction in using the bindings.

For something as simple as language bindings, it's much better to keep it working across as many versions of Python as possible, especially if those versions are still in active use.

**Comment by bmw** [comment]
Thanks for pinging me about this. Feel free to go ahead and make this change as the only installation mechanism we support for Python 2.6 users has all of our dependencies pinned to specific versions and we're planning to drop support for Python 2.6 ourselves in the coming months.

**Comment by lutter** [comment]
Awesome ! Thanks for letting us know.

**Pull request merged**
