### PR TITLE
Attempt to remove libxml2 as a dependency

### LINKED ISSUE #20: Issues building 1.0.0 release
@thedrow I'm working through updating the fedora package, and during the builds i'm seeing some issues.  The latest one looks like a circular dependency.

```
+ /usr/bin/python2 setup.py build '--executable=/usr/bin/python2 -s'
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    url = "http://augeas.net/",
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 387, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/lib64/python2.7/site-packages/cffi/setuptools_ext.py", line 187, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/usr/lib64/python2.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/usr/lib64/python2.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "augeas/ffi.py", line 44, in <module>
    lib = ffi.dlopen("augeas")
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 139, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 769, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 757, in _load_backend_lib
    raise OSError("library not found: %r" % (name,))
OSError: library not found: 'augeas'
```

### PR DESCRIPTION
**Pull request by thedrow**
Fixes #20 #21

### CODE REVIEW

**Comment by thedrow** [comment]
@gregswift @lutter @rackergs @ohemorange can you please try to install this branch? I think I got rid of the direct dependency on libxml2.

**Comment by lutter** [comment]
@thedrow I just tried this on a Fedora 25 machine where I had removed `/usr/include/libxml2`, and the following worked successfully for me:

```
make build
PYTHONPATH=$PWD/build/lib.linux-x86_64-2.7/ make check
```

The change also makes sense to me as `ffi.py` already contains the headers for all the Augeas functions the Python bindings are interested in, and teh include of `augeas.h` was therefore superfluous.

So, +1 from me.

**Comment by gregswift** [comment]
On Fedora 24, with libxml2-devel both installed and uninstalled I get the following 

```
[ xaeth@localhost python-augeas ] (remove-libxml2-dependency *%)$ make build
PREFIX=/usr python setup.py build
running build
running build_py
running build_ext
generating cffi module 'build/temp.linux-x86_64-2.7/augeas.c'
already up-to-date
building 'augeas' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/augeas.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/augeas.o
build/temp.linux-x86_64-2.7/augeas.c:423:35: fatal error: augeas.h: No such file or directory
                #include <augeas.h>
                                   ^
compilation terminated.
error: command 'gcc' failed with exit status 1
Makefile:15: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by gregswift** [comment]
Running `make check` with the PYTHONPATH @lutter used does run clean.  Without the PYTHONPATH being set i get this error

```
test15Copy (__main__.TestAugeas) ... ERROR

======================================================================
ERROR: test15Copy (__main__.TestAugeas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_augeas.py", line 234, in test15Copy
    a.copy(orig_path, copy_path)
AttributeError: 'Augeas' object has no attribute 'copy'

----------------------------------------------------------------------
Ran 15 tests in 9.929s

FAILED (errors=1)
Makefile:4: recipe for target 'check' failed
make[1]: *** [check] Error 1
make[1]: Leaving directory '/home/xaeth/Development/python-augeas/test'
Makefile:24: recipe for target 'check' failed
make: *** [check] Error 2

```

**Comment by lutter** [comment]
@gregswift are you sure you have the patch for this change applied ? You might also have to do a `make clean` (or maybe even blow `build/` away). The errors you got in both attempts at `make build` indicate that the code is still trying to include `augeas.h`, which it shouldn't based on this PR.

**Comment by lutter** [comment]
@thedrow One problem is that `setup.py` requires `cffi >= 1.0.0`, but RHEL/CentOS 6 only come with `python-cffi-0.6`, which means that this new version of the Python bindings won't be available on that platform. Still an improvement to where we are today.

**Comment by gregswift** [comment]
Blew everything away and tried again and it did work.  not sure what got gummed up.

👍

**Comment by lutter** [comment]
Yes, I think the `Makefile` should set the `PYTHONPATH` - I don't see how tests could possibly work against what we just built without setting it.

**Comment by jefferyto** [comment]
Apologies for commenting on a very old PR, but I wanted to point out that by removing the header source parameter for `ffi.set_source()`, this changed the CFFI mode of usage from API to ABI mode (and as I mentioned in #48, it is currently a somewhat confused mix of out-of-line and in-line ABI mode).

From CFFI's documentation, it is clear that API mode is the [preferred mode](https://cffi.readthedocs.io/en/latest/overview.html#abi-versus-api) to use; out-of-line API mode is described as the [main mode of usage](https://cffi.readthedocs.io/en/latest/overview.html#main-mode-of-usage).

Reading through the issues fixed by this change, I see that there were build issues related to libxml2. Perhaps a better solution would have been to set `CPPFLAGS` (or another similar variable) in the Makefile with the correct include path, i.e. based on a call to `pkg-config`.

**Comment by thedrow** [comment]
@jefferyto Feel free to suggest a patch.

**Pull request merged**
