### PR TITLE
Add copy to python-augeas API

### PR DESCRIPTION
**Pull request by davidkupka**

### CODE REVIEW

**Comment by davidkupka** [comment]
The failure reported by Travis CI is caused by old libaugeas (1.0.0) on Ubuntu. Could you please update it to at least 1.2.0? aug_cp() was added in 1.2.0, I could update spec file to require at least 1.2.0 but I doubt it will change anything since Travis is running on Ubuntu.

**Comment by davidkupka** [comment]
I've changed the .travis.yml to download and install augeas-1.2.0 (https://github.com/davidkupka/python-augeas/commit/4286cb85ebd60de506be5c5792a6637775182c03) and everything works.
I know that it is quite a hack but I don't know other way to get newer augeas to old Ubuntu 12.04 ...

**Comment by domcleal** [comment]
@davidkupka try this: https://github.com/hercules-team/ruby-augeas/blob/master/.travis.yml#L8-L12

**Comment by davidkupka** [comment]
@domcleal Thanks, it works :) Should I add a patch for the .travis.yml?

**Comment by domcleal** [comment]
Yep, go for it!

**Comment by gregswift** [comment]
:+1:

**Comment by davidkupka** [comment]
@domcleal Could you please merge the pull request? Or is there anything that I should do?

**Comment by domcleal** [comment]
Sure, thanks @davidkupka and @gregswift.

**Pull request merged**
