### PR TITLE
Rewrote the extension code in CFFI

### PR DESCRIPTION
**Pull request by thedrow**
This has multiple advantages:
- It allows us to support PyPy. The match() method used CPython specific API with ctypes and that didn't work on PyPy.
- It's faster than ctypes even on CPython.

It does require cffi and setuptools but all python developers have those installed.
All the tests pass. Let me know if something is wrong so I can fix it.

### CODE REVIEW

**Comment by raphink** [comment]
I'll try to take some time to review later. Could you squash into passing commits only already?

**Comment by thedrow** [comment]
@raphink Of course I can :)

**Comment by thedrow** [comment]
@raphink Done :)

**Comment by thedrow** [comment]
@raphink Ping?

**Comment by thedrow** [comment]
@raphink I managed to free the matches array so it should all be good to merge. No more issues.
I'll add more features later.

**Pull request merged**
